dev:
    csv_file: ../data/url_lists/test_urls.csv
    warc_folder: ../data/warcs/
    db_folder: ../data/db/
    track_failed_urls: True
    new_failed_url_list: False
    failed_url_list: ../data/url_lists/failed_URLs.txt

prod:
    csv_file: ../data/url_lists/subdomain_list.txt
    warc_folder: ../data/extracted/
    db_folder: ../data/db/
    track_failed_urls: True
    new_failed_url_list: False
    failed_url_list: ../data/url_lists/failed_URLs.txt