dev:
    csv_file: ../data/url_lists/test_urls.csv
    output_base: ../public/
    extraction_input_folder: ../data/warcs/
    db_folder: ../data/db/
    extraction_output_folder: ../data/extracted/

prod:
    csv_file: ../data/url_lists/CDC_html_URLs_from_sitemap_data_-_20241201.csv
    output_base: ../public/
    extraction_input_folder: ../data/extracted/
    db_folder: ../data/db/
    extraction_output_folder: ../data/extracted_html/
